"""extend document metadata

Revision ID: 341ea2afd8e1
Revises: d1dea2d32c74
Create Date: 2026-05-03 13:39:28.302316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341ea2afd8e1'
down_revision: Union[str, Sequence[str], None] = 'd1dea2d32c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('checksum_sha256', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('storage_bucket', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('storage_key', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'storage_key')
    op.drop_column('documents', 'storage_bucket')
    op.drop_column('documents', 'checksum_sha256')
    op.drop_column('documents', 'file_size_bytes')
    # ### end Alembic commands ###
